# .travis.yml
language: php
dist: bionic

php:
- 7.3

services:
  - mysql

cache:
    directories:
      - node_modules
      - vendor
  
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan migrate

after_script:
- php artisan jwt:secret

script:
- vendor/bin/phpunit
